### ISSUE TITLE
Actividad 3-Cuadro comparativo/Daisy Gonzalez Lita

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Daisy-GonzalezLita12#1]
Actividad 3-Cuadro comparativo
Alumna: Daisy Gonzalez Lita
Grupo: 1BS
[Cuadro comparativo_Daisy_GL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Daisy-GonzalezLita12/files/9465219/Cuadro.comparativo_Daisy_GL.pdf)

**Comment by AmeliReyesHernandez** [comment]
19.4 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
